import { CharacterParts } from "./types";

export const characterParts: CharacterParts = {
  Background: [
    { id: 0, name: "Gray", image: "/assets/background/gray.png" },
    { id: 1, name: "Green", image: "/assets/background/green.png" },
    { id: 2, name: "Indigo", image: "/assets/background/indigo.png" },
    { id: 3, name: "Light Blue", image: "/assets/background/light-blue.png" },
    { id: 4, name: "Light Purple", image: "/assets/background/light-purple.png" },
    { id: 5, name: "Orange", image: "/assets/background/orange.png" },
    { id: 6, name: "Pink", image: "/assets/background/pink.png" },
    { id: 7, name: "Purple", image: "/assets/background/purple.png" },
    { id: 8, name: "Red", image: "/assets/background/red.png" },
    { id: 9, name: "Turquoise", image: "/assets/background/turquoise.png" },
    { id: 10, name: "Yellow", image: "/assets/background/yellow.png" },
    { id: 11, name: "Sky", image: "/assets/background/sky.png" },
  ],
  Skin: [
    { id: 0, name: "Alien", image: "/assets/Skin/alien.png" },
    { id: 1, name: "Dark", image: "/assets/Skin/dark.png" },
    { id: 2, name: "Red", image: "/assets/Skin/red.png" },
    { id: 3, name: "Pink", image: "/assets/Skin/pink.png" },
    { id: 4, name: "Brown", image: "/assets/Skin/brown.png" },
    { id: 5, name: "Light Brown", image: "/assets/Skin/light-brown.png" },
    { id: 6, name: "Skeleton", image: "/assets/Skin/skeleton.png" },
    { id: 7, name: "Solana", image: "/assets/Skin/solana.png" },
    { id: 8, name: "Zombie", image: "/assets/Skin/zombie.png" },
    { id: 9, name: "Yellow", image: "/assets/Skin/yellow.png" },
    { id: 10, name: "Purple", image: "/assets/Skin/purple.png" },
  ],
  Cheeks: [
    { id: 0, name: "None", image: "/assets/Cheeks/none.png" },
    { id: 1, name: "Rosy Cheeks", image: "/assets/Cheeks/rosy-cheeks.png" },
  ],
  Earrings: [
    { id: 0, name: "None", image: "/assets/Earrings/none.png" },
    { id: 1, name: "Silver Stud", image: "/assets/Earrings/silver-stud.png" },
    { id: 2, name: "Silver Hoop", image: "/assets/Earrings/silver-hoop.png" },
    { id: 3, name: "Gold Hoop", image: "/assets/Earrings/gold-hoop.png" },
    { id: 4, name: "Diamond Stud", image: "/assets/Earrings/diamond-stud.png" },
  ],
  Headwear: [
    { id: 0, name: "None", image: "/assets/Headwear/none.png" },
    { id: 1, name: "Black Backwards Cap", image: "/assets/Headwear/black-backwards-cap.png" },
    { id: 2, name: "Black Cap", image: "/assets/Headwear/black-cap.png" },
    { id: 3, name: "Black Fedora", image: "/assets/Headwear/black-fedora.png" },
    { id: 4, name: "Black Headset", image: "/assets/Headwear/black-headset.png" },
    { id: 5, name: "Blue Backwards Cap", image: "/assets/Headwear/blue-backwards-cap.png" },
    { id: 6, name: "Blue Bandana", image: "/assets/Headwear/blue-bandana.png" },
    { id: 7, name: "Blue Beanie", image: "/assets/Headwear/blue-beanie.png" },
    { id: 8, name: "Blue Cap", image: "/assets/Headwear/blue-cap.png" },
    { id: 9, name: "Blue Headset", image: "/assets/Headwear/blue-headset.png" },
    { id: 10, name: "Blue Punk Hair", image: "/assets/Headwear/blue-punk-hair.png" },
    { id: 11, name: "Bow", image: "/assets/Headwear/bow.png" },
    { id: 12, name: "Flower Bandana", image: "/assets/Headwear/flower-bandana.png" },
    { id: 13, name: "Green Backwards Cap", image: "/assets/Headwear/green-backwards-cap.png" },
    { id: 14, name: "Green Beanie", image: "/assets/Headwear/green-beanie.png" },
    { id: 15, name: "Green Cap", image: "/assets/Headwear/green-cap.png" },
    { id: 16, name: "Green Punk Hair", image: "/assets/Headwear/green-punk-hair.png" },
    { id: 17, name: "Halo", image: "/assets/Headwear/halo.png" },
    { id: 18, name: "Hot Head", image: "/assets/Headwear/hot-head.png" },
    { id: 19, name: "Lilac Bandana", image: "/assets/Headwear/lilac-bandana.png" },
    { id: 20, name: "Military Helmet", image: "/assets/Headwear/military-helmet.png" },
    { id: 21, name: "Ninja Bandana", image: "/assets/Headwear/ninja-bandana.png" },
    { id: 22, name: "Noble Crown", image: "/assets/Headwear/noble-crown.png" },
    { id: 23, name: "Orange Backwards Cap", image: "/assets/Headwear/orange-backwards-cap.png" },
    { id: 24, name: "Orange Cap", image: "/assets/Headwear/orange-cap.png" },
    { id: 25, name: "Pink Beanie", image: "/assets/Headwear/pink-beanie.png" },
    { id: 26, name: "Pink Headset", image: "/assets/Headwear/pink-headset.png" },
    { id: 27, name: "Pirate Headset", image: "/assets/Headwear/pirate-bandana.png" },
    { id: 28, name: "Propeller Hat", image: "/assets/Headwear/propeller-hat.png" },
    { id: 29, name: "Purple Headset", image: "/assets/Headwear/purple-headset.png" },
    { id: 30, name: "Red Bandana", image: "/assets/Headwear/red-bandana.png" },
    { id: 31, name: "Red Punk Hair", image: "/assets/Headwear/red-punk-hair.png" },
    { id: 32, name: "Red Shroom Hat", image: "/assets/Headwear/red-shroom-hat.png" },
    { id: 33, name: "Sailor Hat", image: "/assets/Headwear/sailor-hat.png" },
    { id: 34, name: "Shroom Hat", image: "/assets/Headwear/shroom-hat.png" },
    { id: 35, name: "Sombrero", image: "/assets/Headwear/sombrero.png" },
    { id: 36, name: "Space Warrior", image: "/assets/Headwear/space-warrior.png" },
    { id: 37, name: "Top Hat", image: "/assets/Headwear/top-hat.png" },
    { id: 38, name: "Viking Helmet", image: "/assets/Headwear/viking-helmet.png" },
    { id: 39, name: "White Fedora", image: "/assets/Headwear/white-fedora.png" },
    { id: 40, name: "White Headset", image: "/assets/Headwear/white-headset.png" },
  ],
  Clothes: [
    { id: 0, name: "None", image: "/assets/clothes/none.png" },
    { id: 1, name: "Poncho", image: "/assets/clothes/poncho.png" },
    { id: 2, name: "Red Shirt", image: "/assets/clothes/red-shirt.png" },
    { id: 3, name: "Purple Shirt", image: "/assets/clothes/purple-shirt.png" },
    { id: 4, name: "Blue Shirt", image: "/assets/clothes/blue-shirt.png" },
    { id: 5, name: "Green Shirt", image: "/assets/clothes/green-shirt.png" },
    { id: 6, name: "Brown Shirt", image: "/assets/clothes/brown-shirt.png" },
    { id: 7, name: "Orange Shirt", image: "/assets/clothes/orange-shirt.png" },
    { id: 8, name: "Hawaiian Shirt", image: "/assets/clothes/hawaiian-shirt.png" },
    { id: 9, name: "Sailor Shirt", image: "/assets/clothes/sailor-shirt.png" },
    { id: 10, name: "Suspenders", image: "/assets/clothes/suspenders.png" },
    { id: 11, name: "Armor", image: "/assets/clothes/armor.png" },
    { id: 12, name: "Baby Vest", image: "/assets/clothes/baby-vest.png" },
    { id: 13, name: "Military Vest", image: "/assets/clothes/military-vest.png" },
    { id: 14, name: "Stunt Suit", image: "/assets/clothes/stunt-suit.png" },
    { id: 15, name: "Diamond", image: "/assets/clothes/diamond.png" },
    { id: 16, name: "King's Robe", image: "/assets/clothes/kings-robe.png" },
    { id: 17, name: "Queen's Robe", image: "/assets/clothes/queens-robe.png" },
],
  Eyes: [
    { id: 0, name: "None", image: "/assets/eyes/none.png" },
    { id: 1, name: "Cool Glasses", image: "/assets/eyes/cool-glasses.png" },
    { id: 2, name: "Nerd Glasses", image: "/assets/eyes/nerd-glasses.png" },
    { id: 3, name: "Purple Glasses", image: "/assets/eyes/purple-glasses.png" },
    { id: 4, name: "Yellow Glasses", image: "/assets/eyes/yellow-glasses.png" },
    { id: 5, name: "3D Glasses", image: "/assets/eyes/3d-glasses.png" },
    { id: 6, name: "Sunset Vipers", image: "/assets/eyes/sunset-vipers.png" },
    { id: 7, name: "Solana Vipers", image: "/assets/eyes/solana-vipers.png" },
    { id: 8, name: "VR Goggles", image: "/assets/eyes/vr-goggles.png" },
    { id: 9, name: "Lazer Eyes", image: "/assets/eyes/lazer-eyes.png" },
    
  ],
  Accessories: [
    { id: 0, name: "None", image: "/assets/Accessories/none.png" },
    { id: 1, name: "Baby Powder", image: "/assets/Accessories/baby-powder.png" },
    { id: 2, name: "Blue Pacifier", image: "/assets/Accessories/blue-pacifier.png" },
    { id: 3, name: "Bottle", image: "/assets/Accessories/bottle.png" },
    { id: 4, name: "Bubbles", image: "/assets/Accessories/bubbles.png" },
    { id: 5, name: "Candy Cig", image: "/assets/Accessories/candy-cig.png" },
    { id: 6, name: "Pink Bottle", image: "/assets/Accessories/pink-bottle.png" },
    { id: 7, name: "Pink Pacifier", image: "/assets/Accessories/pink-pacifier.png" },
    { id: 8, name: "Red Birdie", image: "/assets/Accessories/red-birdie.png" },
  ],
  special: [
    { id: 0, name: "None", image: "/assets/special/none.png" },
    { id: 1, name: "Bus Ring", image: "/assets/special/bus-ring.png" },
    { id: 2, name: "Fire Ring", image: "/assets/special/fire-ring.png" },
  ],
};
